name: Echo Organization Secret

on:
  workflow_dispatch:

jobs:
  echo_secret:
    name: Echo Organization Secret
    runs-on: ubuntu-latest
    steps:
      - name: Print Organization Secret
        run: echo ${{ secrets.TEST_ORGANIZATION_SECRET }}
        env:
          ORGANIZATION_SECRET: ${{ secrets.TEST_ORGANIZATION_SECRET }}
